edition = "2024"
unstable_features = true

condense_wildcard_suffixes = true
format_macro_bodies = true
use_try_shorthand = true

imports_layout = "Vertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

match_arm_leading_pipes = "Always"
match_block_trailing_comma = true

normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true

overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 16
struct_lit_width = 32
struct_variant_width = 32
use_field_init_shorthand = true

fn_single_line = true
single_line_if_else_max_width = 80
single_line_let_else_max_width = 80

trailing_semicolon = false
tab_spaces = 4
