# The default log level `to` uses
log_level = "trace"

# Whether to run tests
tests = true

# Whether to strip debugging symbols from binaries
strip = true

# Flags passed to `make`
makeflags = "-j16"

# A good more generic alternative might be '-march=x86-64-v3 -O2 -pipe'
cflags = "-march=native -O3 -pipe -fno-semantic-interposition -fomit-frame-pointer"

# The stagefile to use in the build environment
stagefile = "/var/cache/lfstage/profiles/to/stages/lfstage-to-2025-07-10_22-52-27.tar.xz"

# The server address for the fileserver hosting distfiles
server_address = "http://127.0.0.1:7020"

# Package repository options
package_repo = "https://github.com/Toxikuu/to-pkgs.git"
package_repo_branch = "master"

# A good minimal alternative is `tree -CF -- *`
tree_command = "eza -T --color=always --icons=always -F=always --no-quotes -la --total-size -- *"
