log_level = "trace"
tests = true
strip = true
# jobs = 16
cflags = "-march=native -O2 -pipe"
server_address = "127.0.0.1:7020"
package_repo = "https://github.com/Toxikuu/to-pkgs.git"
package_repo_branch = "not-systemd"
