#!/usr/bin/env bash

set -e
pushd . &>/dev/null

n="${1%@*}" # leniently split the version field
n="${n,,}"

cd /var/cache/to/pkgs/"$n"

check_existence() {
    if [ ! -e "pkg" ]; then
        echo "Package '$n' does not exist" >&2
        exit 2
    fi
}

finalize() {

    . ./pkg

    to lint      "$n" || return 2
    to generate  "$n" || return 3
    to vf        "$n" | sed 's,\x1b\[[0-9;]*m,,g' | grep '^\[-\] ' && return 99

    if ! $SKIP_BUILD; then
        to build "$n" || return 4
    fi

    if [ -z "$(git status -s .)" ]; then
        echo "No changes made"
        return 0
    fi

    git add .
    COMMIT=$(mktemp)
    sed \
        -e "s,<name>,$n,g"      \
        -e "s,<version>,$v,g"   \
    /usr/share/to/git-templates/edit-package > "$COMMIT"
    git commit --template="$COMMIT"

    rm -f "$COMMIT"

}


# trap myself until the package builds :100:
bash --rcfile /usr/share/to/envs/p.env
until finalize; do
    echo "Failed to finalize ($?) -- retrying..."
    sleep 0.5
    bash --rcfile /usr/share/to/envs/p.env
done


popd &>/dev/null
